### ISSUE TITLE
Times out after 100 seconds

### ISSUE THREAD

**Issue by icnatejackson** [Duber/vsts-smoke-web-test-task#2]
I wanted to use this script to get my website running after a fresh deployment.  At times, my site takes more than 100 seconds to cold boot if there are data and schema migrations that are happening.  

This smoke test Task doesn't set the timeout of the underlying web request, and results in a HTTP code of 0 if the server doesn't respond within 100 seconds.

It would be nice for it to ask for and apply a timeout value.

**Comment by Duber** [comment]
First of all, sorry for the delay.

That would be a nice addition indeed. I'll take it into account and implement it as soon as possible.
Otherwise, you can also add it yourself and make a pull request ^_^

**Comment by Duber** [comment]
Hello,

I have updated the extension. Now timeout can be configured.



<img width="858" alt="screen shot 2017-07-02 at 23 12 14" src="https://user-images.githubusercontent.com/999284/27773530-f14c36fe-5f7b-11e7-9ca6-fc656bfef77b.png">
