### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by artisticcheese** [Duber/vsts-smoke-web-test-task#3]
1. Ability to change GET/POST
2. Ability to add HTTP "header"
3. Ability to analyze content of response using regex

**Comment by Duber** [comment]
Very nice suggestions @artisticcheese.  I'll try to look into them.

Also, I accept pull request in case you fancy implementing them yourself ^_^

**Comment by artisticcheese** [comment]
I'm new to GIT, how do I `pull`? Clicking on `Pull` button does not allow me to pull

**Comment by Duber** [comment]
@artisticcheese you can't work directly into this repo. You will have to fork it into your account, add the functionality you want and then submit a pull request asking for the features of your repository to be merged into the main repository.

You can find more info at [Github guide to forking](https://guides.github.com/activities/forking/)

**Comment by frankfuu** [comment]
I agree with @artisticcheese, havin the ability to analyze content of the response would be useful. For example, I'm currently using the [Application Initialization module](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization) which allows me to use remap requests to a static html while the my website warms up (takes around 1-2 minutes). 

```
<applicationInitialization
    remapManagedRequestsTo="Startup.htm" 
    skipManagedModules="true" >
  <add initializationPage="/default.aspx" />
</applicationInitialization>
```

Problem is, the static html `Startup.htm` returned has a status code of 200. If there was a way where I can see, check for the keywords "my site is warming up now", then reject and retry for N times, this would be immensely useful.

**Comment by jeffpriz** [comment]
@Duber I've submitted a pull request to add retry functionality to the task.  I'd love if that functionality got accepted.  I'd also like to work to add multiple url/server functionality to the task.. not sure if this repo is still active or not though..

**Comment by Duber** [comment]
Ey, hello, sorry for the absence. I will review and proceed to merge PRs
